title: u3d-framework
description: Simple and powerful u3d-framework
theme: jekyll-theme-cayman
show_downloads: true

zip_url:  https://codeload.github.com/hellowod/u3d-framework/zip/master
tar_url: https://github.com/hellowod/u3d-framework/tarball/master